name: NASA Project CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version 18
        uses: actions/setup-node@v2
        with: 
          node-version: '18'
      - run: yarn install
      - run: cd client && yarn run build